apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-booking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flight-booking
  template:
    metadata:
      labels:
        component: flight-booking
    spec:
      containers:
        - name: book-flight
          image: kamligupta/flight-booking
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: flight-booking-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flight-booking-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80